apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # name of the ClusterRole
  name: nginx-ingress-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "nodes", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: nginx-ingress-serviceaccount
  namespace: dev
roleRef:
  kind: ClusterRole
  name: nginx-ingress-cluster-role
  apiGroup: rbac.authorization.k8s.io
